---
title: "Git e GitHub"
author: "Marília Melo Favalesso"
date: "19/11/2020"
output: md_document
---

# Introdução ao Git e ao GitHub

O *Git* é um software de controle de versões que tem como objetivo gerenciar arquivos texto, principalmente códigos de programação. O funcionamento dessa ferramenta é semelhante aos sistemas de nuvens (Google Drive, Dropbox, Mega, etc), em que podemos compartilhar as edições de um script com uma equipe, além de retomar antigas versões de nossos arquivos. Resumidamente, o *Git* examina as mudanças realizadas nos arquivos de um diretório e vai guardando essas informações para compartilhar com outros usuários e/ou possibilitar a reversão de alterações realizadas. Além de ser uma ferramenta extremamente útil, o *Git* se conecta ao serviço de hospedagem e armazenamento de versões chamado *GitHub*. A partir do *GitHub* é possível contribuir com projetos de qualquer lugar do mundo, além de compartilhar os nossos próprios códigos com fins de divulgação e/ou colaboração.

Existem diversas maneiras de trabalhar com o Git e o GitHub. Aqui você poderá eleger algumas opções para aprender!

1. Git e GitHub com o RStudio.
2. Git e GitHub com o Python. 